Feature/buffer mode
0xbadfca11/makevhdx pull request #3
Opened 2018-10-19 09:44 UTC by AGritsevich

This merge request exist like result of implementing issue https://github.com/dokan-dev/dokany/issues/627.
Add feature to get header/footer as buffer, instead of writing to file. It help to importing header/footer as
a byte buffer for use with memory only implementations.
And refactored code into additional headers and c files.
Base class does not assume a full image exists, includes only capability for generating header/footer.

2018-10-19 12:24 UTC, 0xbadfca11 requested changes
When ``VHD[X]_Image::ConstructHeader(is_fixed == false)``, will call SetFileInformationByHandle with an uninitialized value, and abort.

2018-10-24 12:05 UTC, AGritsevich commented
@0xbadfca11, can you mark this place in code and say little more about this situation? I can't understood about witch place you are talking.

2018-10-25 12:06 UTC, 0xbadfca11 commented
```c++
void VHD_Image::ConstructHeader(UINT64 disk_size, UINT32 block_size, UINT32 sector_size, bool is_fixed)
{
  // 1. eof_info is uninitialized memory.
  FILE_END_OF_FILE_INFO eof_info;
  VHD::ConstructHeader(disk_size, block_size, sector_size, is_fixed, eof_info);
  // 3. eof_info still uninitialized.
  if (!SetFileInformationByHandle(image, FileEndOfFileInfo, &eof_info, sizeof eof_info))
  {
    die();
  }
}
void VHD::ConstructHeader(UINT64 disk_size, UINT32 block_size, UINT32 sector_size, bool is_fixed, FILE_END_OF_FILE_INFO &eof_info)
{
  if (is_fixed)
  {
    eof_info.EndOfFile.QuadPart = disk_size + sizeof vhd_footer;
  }
  else
  {
    // 2. Nothing to did to eof_info.
  }
}
```
VHDX_Image::ConstructHeader same too.

2018-10-25 12:20 UTC, 0xbadfca11 commented
To be honest, features creating an image in memory is not needs for this tool.

2018-10-26 09:04 UTC, AGritsevich commented
@0xbadfca11, pleace look at [Dokan project](https://github.com/dokan-dev/dokany). We're using buffered makevhdx and Dokan mirroring functionality create tool that can mirror some drive to vhdx file, then this disk attaching to  OS file system. It tool can be used for real time decrypt disks. You insert encrypted disk, real disk hidden, and in file system appear after authentication virtual regular disk. 
Cool?

2025-10-01 11:38 UTC, closed without merging